### ISSUE TITLE
App not available for Mac 

### ISSUE THREAD

**Issue by ccfreem** [ImpulseRC/OSD#107]
I am unable to download the software via the link https://apps.apple.com/us/app/impulseosd/id1416313087 provided on the downloads page here https://impulserc.com/pages/downloads

I am given an error stating "This app is currently not available in your country or region.". Is this expected behavior for the US?

**Comment by sblakemore** [comment]
Very sorry for the confusion. The firmware has not been in active development for some time and the hardware was discontinued early during COVID because it became impossible to source the components. Because of this along with the lack of many users of the Mac app we stopped paying the Apple Store fee some time ago. 

We have edited the downloads page to remove that link and the windows app should still work if that helps at all. Very sorry for the inconvenience.
